In [1]:
import pandas as pd
use_cols = [i for i in range(4)]
df = pd.read_excel('.\附件1.xlsx', sheet_name=1)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

,编号,速度(km/h),电量消耗速率(kW·h/km),初始站点,无人车配送范围（路段）,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42
0,无人车1,15.7,0.050,16,"1,2","2,3","3,4","3,6","4,5","6,7",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,无人车2,21.9,0.050,34,"2,3","3,4","3,6","4,5","6,7","7,8",...,"31,32","31,33","33,34",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,无人车3,17.1,0.049,13,"3,4","3,6","4,5","6,7","7,8","8,9",...,"31,32","31,33","33,34","35,36","35,39","36,37","36,38","39,41","39,40","41,42"
3,无人车4,16.5,0.058,13,"6,7","7,8","8,9","9,10","9,11","11,13",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,无人车5,20.1,0.051,24,"8,9","9,14","14,17","17,25","17,21","17,18",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,无人车6,18.2,0.071,24,"14,17","17,25","17,21","17,18","18,20","18,19",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,无人车7,23.2,0.072,30,"17,25","25,30","30,35","35,43","43,44","44,45",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,无人车8,20.2,0.044,61,"35,43","43,44","44,45","45,46","46,47","47,52",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,无人车9,23.8,0.063,56,"43,44","44,45","45,46","46,47","47,52","52,53",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,无人车10,21.8,0.069,51,"44,45","45,46","46,47","47,48","48,50","48,49",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,无人车11,24.3,0.056,45,"45,46","46,47","47,52",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,无人车12,17.4,0.059,82,"57,62","62,63","63,66","66,74","74,75","75,76",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,无人车13,22.1,0.043,73,"57,62","62,63","63,66","66,74","66,70","66,67",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,无人车14,21.3,0.053,83,"63,66","66,74","74,75","75,76","76,77","77,78",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,无人车15,18.0,0.046,78,"75,76","76,77","77,78","78,83","83,84",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,无人车16,21.6,0.058,84,"77,78","78,83","83,84","84,85","85,90","90,93",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,无人车17,18.2,0.064,89,"78,83","83,84","84,85","85,86","86,88","86,87",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,无人车18,15.3,0.063,89,"83,84","84,85","85,90","85,86","86,88","86,87",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,无人车19,15.1,0.061,104,"84,85","85,90","90,93","93,101","101,102","102,105",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,无人车20,17.4,0.041,90,"85,90","90,93","93,101","101,102","102,105","105,106",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df.set_index(['编号'])
df.index += 1

In [3]:
df.drop(columns=['编号'])

,速度(km/h),电量消耗速率(kW·h/km),初始站点,无人车配送范围（路段）,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42
1,15.7,0.050,16,"1,2","2,3","3,4","3,6","4,5","6,7","7,8",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21.9,0.050,34,"2,3","3,4","3,6","4,5","6,7","7,8","8,9",...,"31,32","31,33","33,34",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,17.1,0.049,13,"3,4","3,6","4,5","6,7","7,8","8,9","9,14",...,"31,32","31,33","33,34","35,36","35,39","36,37","36,38","39,41","39,40","41,42"
4,16.5,0.058,13,"6,7","7,8","8,9","9,10","9,11","11,13","11,12",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,20.1,0.051,24,"8,9","9,14","14,17","17,25","17,21","17,18","18,20",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,18.2,0.071,24,"14,17","17,25","17,21","17,18","18,20","18,19","21,22",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,23.2,0.072,30,"17,25","25,30","30,35","35,43","43,44","44,45","45,46",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,20.2,0.044,61,"35,43","43,44","44,45","45,46","46,47","47,52","52,57",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,23.8,0.063,56,"43,44","44,45","45,46","46,47","47,52","52,53","52,54",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,21.8,0.069,51,"44,45","45,46","46,47","47,48","48,50","48,49","50,51",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,24.3,0.056,45,"45,46","46,47","47,52",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,17.4,0.059,82,"57,62","62,63","63,66","66,74","74,75","75,76","76,77",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,22.1,0.043,73,"57,62","62,63","63,66","66,74","66,70","66,67","67,68",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,21.3,0.053,83,"63,66","66,74","74,75","75,76","76,77","77,78","78,83",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,18.0,0.046,78,"75,76","76,77","77,78","78,83","83,84",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,21.6,0.058,84,"77,78","78,83","83,84","84,85","85,90","90,93","93,101",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18.2,0.064,89,"78,83","83,84","84,85","85,86","86,88","86,87","88,89",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,15.3,0.063,89,"83,84","84,85","85,90","85,86","86,88","86,87","88,89",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,15.1,0.061,104,"84,85","85,90","90,93","93,101","101,102","102,105","102,103",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,17.4,0.041,90,"85,90","90,93","93,101","101,102","102,105","105,106","106,111",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
road = pd.read_excel('.\附件1.xlsx')
road

,Unnamed: 0,站点1,站点2,站点3,站点4,站点5,站点6,站点7,站点8,站点9,...,站点113,站点114,站点115,站点116,站点117,站点118,站点119,站点120,站点121,站点122
0,站点1,NaN,8.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,站点2,8.4,NaN,4.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,站点3,NaN,4.5,NaN,5.3,NaN,1.6,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,站点4,NaN,NaN,5.3,NaN,5.1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,站点5,NaN,NaN,NaN,5.1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,站点118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,9.1,NaN,NaN,NaN,NaN,NaN
118,站点119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.6,NaN,NaN,5.0,NaN,NaN
119,站点120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN
120,站点121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,1.1
121,站点122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.1,NaN

In [86]:
lists = [[] for _ in range(40)]
i = 0
for index, row in df.iterrows():
    for col in range(4, len(df.columns)):
        if not pd.isna(row.iloc[col]):
            lists[2 * i].append(int(row.iloc[col].split(',')[0]))
            lists[2 * i + 1].append(int(row.iloc[col].split(',')[1]))
    i += 1
for j in range(len(lists)):
    print(lists[j])

[1, 2, 3, 3, 4, 6, 7, 8, 9, 9, 9, 11, 11, 14, 14, 15, 17, 17, 17, 18, 18, 21, 21, 23, 25, 25, 27, 27]
[2, 3, 4, 6, 5, 7, 8, 9, 14, 11, 10, 13, 12, 15, 17, 16, 21, 18, 25, 20, 19, 22, 23, 24, 26, 27, 28, 29]
[2, 3, 3, 4, 6, 7, 8, 9, 9, 9, 11, 11, 14, 14, 15, 17, 17, 17, 18, 18, 21, 21, 23, 25, 25, 25, 27, 27, 30, 31, 31, 33]
[3, 4, 6, 5, 7, 8, 9, 14, 11, 10, 13, 12, 15, 17, 16, 21, 18, 25, 20, 19, 22, 23, 24, 26, 27, 30, 28, 29, 31, 32, 33, 34]
[3, 3, 4, 6, 7, 8, 9, 9, 9, 11, 11, 14, 14, 15, 17, 17, 17, 18, 18, 21, 21, 23, 25, 25, 25, 27, 27, 30, 30, 31, 31, 33, 35, 35, 36, 36, 39, 39, 41]
[4, 6, 5, 7, 8, 9, 14, 11, 10, 13, 12, 15, 17, 16, 21, 18, 25, 20, 19, 22, 23, 24, 26, 27, 30, 28, 29, 35, 31, 32, 33, 34, 36, 39, 37, 38, 41, 40, 42]
[6, 7, 8, 9, 9, 11, 11]
[7, 8, 9, 10, 11, 13, 12]
[8, 9, 14, 17, 17, 17, 18, 18, 21, 21, 23, 25, 30, 35, 43, 44, 45]
[9, 14, 17, 25, 21, 18, 20, 19, 22, 23, 24, 30, 35, 43, 44, 45, 46]
[14, 17, 17, 17, 18, 18, 21, 21, 23, 25, 30]
[17, 25, 21, 18, 20, 19, 22, 23, 24, 30, 35]
[17, 25, 30, 35, 43, 44, 45, 46, 47, 52, 57]
[25, 30, 35, 43, 44, 45, 46, 47, 52, 57, 62]
[35, 43, 44, 45, 46, 47, 52, 57, 58, 58, 60]
[43, 44, 45, 46, 47, 52, 57, 58, 59, 60, 61]
[43, 44, 45, 46, 47, 52, 52, 54, 54]
[44, 45, 46, 47, 52, 53, 54, 55, 56]
[44, 45, 46, 47, 48, 48, 50]
[45, 46, 47, 48, 50, 49, 51]
[45, 46, 47]
[46, 47, 52]
[57, 62, 63, 66, 74, 75, 76, 77, 78, 78, 79, 79, 81, 83, 84]
[62, 63, 66, 74, 75, 76, 77, 78, 83, 79, 81, 80, 82, 84, 85]
[57, 62, 63, 66, 66, 66, 67, 67, 70, 70, 72, 74, 75, 76, 77]
[62, 63, 66, 74, 70, 67, 68, 69, 71, 72, 73, 75, 76, 77, 78]
[63, 66, 74, 75, 76, 77, 78]
[66, 74, 75, 76, 77, 78, 83]
[75, 76, 77, 78, 83]
[76, 77, 78, 83, 84]
[77, 78, 83, 84, 85, 90, 93]
[78, 83, 84, 85, 90, 93, 101]
[78, 83, 84, 85, 86, 86, 88]
[83, 84, 85, 86, 88, 87, 89]
[83, 84, 85, 85, 86, 86, 88]
[84, 85, 90, 86, 88, 87, 89]
[84, 85, 90, 93, 101, 102, 102, 103, 105, 106, 111, 116, 121]
[85, 90, 93, 101, 102, 105, 103, 104, 106, 111, 116, 121, 122]
[85, 90, 93, 101, 102, 105, 106]
[90, 93, 101, 102, 105, 106, 111]

In [90]:
position = 122
for i in range(20):
    for j in lists[2 * i + 1]:
        if j == position:
            for k in

2
3
4
6
5
7
8
9
14
11
10
13
12
15
17
16
21
18
25
20
19
22
23
24
26
27
28
29
3
4
6
5
7
8
9
14
11
10
13
12
15
17
16
21
18
25
20
19
22
23
24
26
27
30
28
29
31
32
33
34
4
6
5
7
8
9
14
11
10
13
12
15
17
16
21
18
25
20
19
22
23
24
26
27
30
28
29
35
31
32
33
34
36
39
37
38
41
40
42
7
8
9
10
11
13
12
9
14
17
25
21
18
20
19
22
23
24
30
35
43
44
45
46
17
25
21
18
20
19
22
23
24
30
35
25
30
35
43
44
45
46
47
52
57
62
43
44
45
46
47
52
57
58
59
60
61
44
45
46
47
52
53
54
55
56
45
46
47
48
50
49
51
46
47
52
62
63
66
74
75
76
77
78
83
79
81
80
82
84
85
62
63
66
74
70
67
68
69
71
72
73
75
76
77
78
66
74
75
76
77
78
83
76
77
78
83
84
78
83
84
85
90
93
101
83
84
85
86
88
87
89
84
85
90
86
88
87
89
85
90
93
101
102
105
103
104
106
111
116
121
122
90
93
101
102
105
106
111

In [ ]:
def